#!/bin/csh -f

# env http_proxy="http://proxy.fm.intel.com:911" git clone http://github.com/adobe/source-code-pro.git
set script_dir = `dirname $0`
mkdir -p $HOME/.fonts
cd $script_dir
set dirs = `ls -d */`
foreach i ($dirs) 
  cp $i/* $HOME/.fonts/
end
cd $HOME/
fc-cache
mkfontdir
